apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: user-service
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor-auth
      containers:
        - name: user-service
          image: harbor.yellowsunn.com:80/dev/msa-demo-user-service
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 0.5Gi
            limits:
              cpu: 50m
              memory: 0.5Gi
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
      terminationGracePeriodSeconds: 30
