apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: user-service
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
images:
- name: harbor.yellowsunn.com:80/dev/msa-demo-user-service
  newTag: "20240205004538"
