apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-config-server
spec:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      name: home-config-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: harbor-auth
      containers:
        - name: home-config-server
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 0.3Gi
            limits:
              cpu: 200m
              memory: 0.5Gi
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
      terminationGracePeriodSeconds: 30
