apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: msa-demo-apigateway-service
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: msa-demo-apigateway-service
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
