apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: msa-demo-apigateway-service
resources:
- deployment.yaml
- service.yaml
- hpa.yaml
images:
- name: harbor.yellowsunn.com:80/dev/msa-demo-apigateway-service
  newTag: "20240208155858"
