apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-config-server
spec:
  template:
    metadata:
      name: home-config-server
    spec:
      containers:
        - name: home-config-server
          image: harbor.yellowsunn.com:80/prod/home-config-server
          resources:
            requests:
              cpu: 100m
              memory: 0.5Gi
            limits:
              cpu: 300m
              memory: 1Gi
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -javaagent:/pinpoint-agent/pinpoint-bootstrap.jar
                -Dpinpoint.applicationName=PROD-HOME-CONFIG-SERVER
                -Dpinpoint.agentId=prodhomeconfig
                -Dpinpoint.profiler.profiles.active=release
          volumeMounts:
            - mountPath: /logs
              name: logback
      volumes:
        - name: logback
          hostPath:
            path: /var/log/logback/prod/home-config-server
