apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
commonLabels:
  app: prod-home-config-server
resources:
- ../base
patches:
- path: deployment.yaml
  target:
    group: apps
    kind: Deployment
    version: v1
- path: hpa.yaml
  target:
    group: autoscaling
    kind: HorizontalPodAutoscaler
    version: v2
images:
- name: harbor.yellowsunn.com:80/prod/home-config-server
  newTag: "20231121232222"
