apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-config-server
spec:
  template:
    metadata:
      name: home-config-server
    spec:
      containers:
        - name: home-config-server
          image: harbor.yellowsunn.com:80/dev/home-config-server
