apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: home-config-server
spec:
  maxReplicas: 2
  minReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # 평균 CPU 사용량이 50% 이상인 경우 Scale out
