apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 23.4.0
    chart: prometheus
    helm:
      valueFiles:
        - >-
          https://raw.githubusercontent.com/yellowsunn-home-server/kubernetes-manifest/main/prometheus-2.4.0/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true